databases:
  - name: sportshub # Creates a database named 'sportshub'
    ipAllowList: [] # Only allow internal connections
    plan: free

services:
  - type: web
    name: sportshub
    plan: free
    env: ruby # The version is automatically picked up from a .ruby-version file
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sportshub
          property: connectionString # This is a pretty nifty feature of Render that utilizes the connection string from the database we specified at the beginning of this file.
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
